import type { App } from "vue";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faArrowDown,
  faArrowRightFromBracket,
  faArrowRightToBracket,
  faArrowUp,
  faBan,
  faBook,
  faBriefcaseMedical,
  faBullseye,
  faCartShopping,
  faCheck,
  faCompactDisc,
  faDice,
  faDog,
  faDumbbell,
  faEarthAsia,
  faEdit,
  faFaceFrown,
  faFaceSmile,
  faFloppyDisk,
  faHand,
  faHandSparkles,
  faHome,
  faList,
  faMars,
  faMasksTheater,
  faMinus,
  faNoteSticky,
  faPaw,
  faPerson,
  faPlus,
  faQuestion,
  faRotate,
  faSeedling,
  faTable,
  faTimes,
  faTrash,
  faUser,
  faUserTie,
  faVenus,
  faVial,
  faWandSparkles,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faArrowDown,
  faArrowRightFromBracket,
  faArrowRightToBracket,
  faArrowUp,
  faBan,
  faBook,
  faBriefcaseMedical,
  faBullseye,
  faCartShopping,
  faCheck,
  faCompactDisc,
  faDice,
  faDog,
  faEdit,
  faDumbbell,
  faEarthAsia,
  faFaceFrown,
  faFaceSmile,
  faFloppyDisk,
  faHand,
  faHandSparkles,
  faHome,
  faList,
  faMars,
  faMasksTheater,
  faMinus,
  faNoteSticky,
  faPaw,
  faPerson,
  faPlus,
  faQuestion,
  faRotate,
  faSeedling,
  faTable,
  faTimes,
  faTrash,
  faUser,
  faUserTie,
  faVenus,
  faVial,
  faWandSparkles,
);

export default function (app: App) {
  app.component("font-awesome-icon", FontAwesomeIcon);
}
