// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokeGame.EntityFrameworkCore;

#nullable disable

namespace PokeGame.EntityFrameworkCore.PostgreSQL.Migrations
{
    [DbContext(typeof(PokemonContext))]
    [Migration("20250812202739_PokeGame_1_0_0")]
    partial class PokeGame_1_0_0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.AbilityEntity", b =>
                {
                    b.Property<int>("AbilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AbilityId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UniqueNameNormalized")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("AbilityId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("DisplayName");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UniqueName");

                    b.HasIndex("UniqueNameNormalized")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.ToTable("Abilities", "Pokemon");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.BattleEntity", b =>
                {
                    b.Property<int>("BattleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BattleId"));

                    b.Property<string>("CancelledBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("CancelledOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ChampionCount")
                        .HasColumnType("integer");

                    b.Property<string>("CompletedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("OpponentCount")
                        .HasColumnType("integer");

                    b.Property<string>("Resolution")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("StartedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("StartedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("BattleId");

                    b.HasIndex("CancelledBy");

                    b.HasIndex("CancelledOn");

                    b.HasIndex("ChampionCount");

                    b.HasIndex("CompletedBy");

                    b.HasIndex("CompletedOn");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Kind");

                    b.HasIndex("Location");

                    b.HasIndex("Name");

                    b.HasIndex("OpponentCount");

                    b.HasIndex("Resolution");

                    b.HasIndex("StartedBy");

                    b.HasIndex("StartedOn");

                    b.HasIndex("Status");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.ToTable("Battles", "Pokemon");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.BattlePokemonEntity", b =>
                {
                    b.Property<int>("BattleId")
                        .HasColumnType("integer");

                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.Property<int>("Accuracy")
                        .HasColumnType("integer");

                    b.Property<int>("Attack")
                        .HasColumnType("integer");

                    b.Property<Guid>("BattleUid")
                        .HasColumnType("uuid");

                    b.Property<int>("Critical")
                        .HasColumnType("integer");

                    b.Property<int>("Defense")
                        .HasColumnType("integer");

                    b.Property<int>("Evasion")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PokemonUid")
                        .HasColumnType("uuid");

                    b.Property<int>("SpecialAttack")
                        .HasColumnType("integer");

                    b.Property<int>("SpecialDefense")
                        .HasColumnType("integer");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.HasKey("BattleId", "PokemonId");

                    b.HasIndex("IsActive");

                    b.HasIndex("PokemonId");

                    b.HasIndex("PokemonUid");

                    b.HasIndex("BattleUid", "PokemonUid")
                        .IsUnique();

                    b.ToTable("BattlePokemon", "Pokemon");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.BattleTrainerEntity", b =>
                {
                    b.Property<int>("BattleId")
                        .HasColumnType("integer");

                    b.Property<int>("TrainerId")
                        .HasColumnType("integer");

                    b.Property<Guid>("BattleUid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOpponent")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TrainerUid")
                        .HasColumnType("uuid");

                    b.HasKey("BattleId", "TrainerId");

                    b.HasIndex("IsOpponent");

                    b.HasIndex("TrainerId");

                    b.HasIndex("TrainerUid");

                    b.HasIndex("BattleUid", "TrainerUid")
                        .IsUnique();

                    b.ToTable("BattleTrainers", "Pokemon");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.EvolutionEntity", b =>
                {
                    b.Property<int>("EvolutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EvolutionId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Friendship")
                        .HasColumnType("boolean");

                    b.Property<string>("Gender")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("HeldItemId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("HeldItemUid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("ItemId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ItemUid")
                        .HasColumnType("uuid");

                    b.Property<int?>("KnownMoveId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("KnownMoveUid")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceUid")
                        .HasColumnType("uuid");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetUid")
                        .HasColumnType("uuid");

                    b.Property<string>("TimeOfDay")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("EvolutionId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("HeldItemId");

                    b.HasIndex("HeldItemUid");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ItemId");

                    b.HasIndex("ItemUid");

                    b.HasIndex("KnownMoveId");

                    b.HasIndex("KnownMoveUid");

                    b.HasIndex("Level");

                    b.HasIndex("SourceId");

                    b.HasIndex("SourceUid");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("TargetId");

                    b.HasIndex("TargetUid");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.ToTable("Evolutions", "Pokemon");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.FormAbilityEntity", b =>
                {
                    b.Property<int>("FormId")
                        .HasColumnType("integer");

                    b.Property<int>("AbilityId")
                        .HasColumnType("integer");

                    b.Property<Guid>("AbilityUid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormUid")
                        .HasColumnType("uuid");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("FormId", "AbilityId");

                    b.HasIndex("AbilityId");

                    b.HasIndex("AbilityUid");

                    b.HasIndex("FormId", "Slot")
                        .IsUnique();

                    b.HasIndex("FormUid", "AbilityUid")
                        .IsUnique();

                    b.HasIndex("FormUid", "Slot")
                        .IsUnique();

                    b.ToTable("FormAbilities", "Pokemon");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.FormEntity", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FormId"));

                    b.Property<byte>("BaseAttack")
                        .HasColumnType("smallint");

                    b.Property<byte>("BaseDefense")
                        .HasColumnType("smallint");

                    b.Property<byte>("BaseHP")
                        .HasColumnType("smallint");

                    b.Property<byte>("BaseSpecialAttack")
                        .HasColumnType("smallint");

                    b.Property<byte>("BaseSpecialDefense")
                        .HasColumnType("smallint");

                    b.Property<byte>("BaseSpeed")
                        .HasColumnType("smallint");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsBattleOnly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMega")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SecondaryType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("SpeciesUid")
                        .HasColumnType("uuid");

                    b.Property<string>("SpriteAlternative")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("SpriteAlternativeShiny")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("SpriteDefault")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("SpriteShiny")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UniqueNameNormalized")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("VarietyId")
                        .HasColumnType("integer");

                    b.Property<Guid>("VarietyUid")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.Property<int>("YieldAttack")
                        .HasColumnType("integer");

                    b.Property<int>("YieldDefense")
                        .HasColumnType("integer");

                    b.Property<int>("YieldExperience")
                        .HasColumnType("integer");

                    b.Property<int>("YieldHP")
                        .HasColumnType("integer");

                    b.Property<int>("YieldSpecialAttack")
                        .HasColumnType("integer");

                    b.Property<int>("YieldSpecialDefense")
                        .HasColumnType("integer");

                    b.Property<int>("YieldSpeed")
                        .HasColumnType("integer");

                    b.HasKey("FormId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("DisplayName");

                    b.HasIndex("Height");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("SpeciesId");

                    b.HasIndex("SpeciesUid");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UniqueName");

                    b.HasIndex("UniqueNameNormalized")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("VarietyUid");

                    b.HasIndex("Version");

                    b.HasIndex("Weight");

                    b.HasIndex("YieldExperience");

                    b.HasIndex("VarietyId", "IsDefault");

                    b.ToTable("Forms", "Pokemon");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.InventoryEntity", b =>
                {
                    b.Property<int>("TrainerId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ItemUid")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("TrainerUid")
                        .HasColumnType("uuid");

                    b.HasKey("TrainerId", "ItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ItemUid");

                    b.HasIndex("Quantity");

                    b.HasIndex("TrainerUid");

                    b.HasIndex("TrainerUid", "ItemUid")
                        .IsUnique();

                    b.ToTable("Inventory", "Pokemon");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.ItemEntity", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("MoveId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MoveUid")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Sprite")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UniqueNameNormalized")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("ItemId");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("DisplayName");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("MoveId");

                    b.HasIndex("MoveUid");

                    b.HasIndex("Price");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UniqueName");

                    b.HasIndex("UniqueNameNormalized")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.ToTable("Items", "Pokemon");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.MoveEntity", b =>
                {
                    b.Property<int>("MoveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MoveId"));

                    b.Property<byte?>("Accuracy")
                        .HasColumnType("smallint");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<byte?>("Power")
                        .HasColumnType("smallint");

                    b.Property<byte>("PowerPoints")
                        .HasColumnType("smallint");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UniqueNameNormalized")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("MoveId");

                    b.HasIndex("Accuracy");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("DisplayName");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Power");

                    b.HasIndex("PowerPoints");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.HasIndex("UniqueName");

                    b.HasIndex("UniqueNameNormalized")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.ToTable("Moves", "Pokemon");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.PokemonEntity", b =>
                {
                    b.Property<int>("PokemonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PokemonId"));

                    b.Property<string>("AbilitySlot")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("Box")
                        .HasColumnType("integer");

                    b.Property<string>("Characteristic")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CurrentTrainerId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CurrentTrainerUid")
                        .HasColumnType("uuid");

                    b.Property<byte>("EggCycles")
                        .HasColumnType("smallint");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<int>("FormId")
                        .HasColumnType("integer");

                    b.Property<Guid>("FormUid")
                        .HasColumnType("uuid");

                    b.Property<byte>("Friendship")
                        .HasColumnType("smallint");

                    b.Property<string>("Gender")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("GrowthRate")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<byte>("Height")
                        .HasColumnType("smallint");

                    b.Property<int?>("HeldItemId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("HeldItemUid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEgg")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsShiny")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MaximumExperience")
                        .HasColumnType("integer");

                    b.Property<int?>("MetAtLevel")
                        .HasColumnType("integer");

                    b.Property<string>("MetDescription")
                        .HasColumnType("text");

                    b.Property<string>("MetLocation")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("MetOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("OriginalTrainerId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OriginalTrainerUid")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnershipKind")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("PokeBallId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PokeBallUid")
                        .HasColumnType("uuid");

                    b.Property<int?>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("SpeciesUid")
                        .HasColumnType("uuid");

                    b.Property<string>("Sprite")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("Stamina")
                        .HasColumnType("integer");

                    b.Property<string>("Statistics")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StatusCondition")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TeraType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("ToNextLevel")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UniqueNameNormalized")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("VarietyId")
                        .HasColumnType("integer");

                    b.Property<Guid>("VarietyUid")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<int>("Vitality")
                        .HasColumnType("integer");

                    b.Property<byte>("Weight")
                        .HasColumnType("smallint");

                    b.HasKey("PokemonId");

                    b.HasIndex("Box");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("CurrentTrainerId");

                    b.HasIndex("CurrentTrainerUid");

                    b.HasIndex("EggCycles");

                    b.HasIndex("Experience");

                    b.HasIndex("FormId");

                    b.HasIndex("FormUid");

                    b.HasIndex("HeldItemId");

                    b.HasIndex("HeldItemUid");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("IsEgg");

                    b.HasIndex("Level");

                    b.HasIndex("Nickname");

                    b.HasIndex("OriginalTrainerId");

                    b.HasIndex("OriginalTrainerUid");

                    b.HasIndex("PokeBallId");

                    b.HasIndex("PokeBallUid");

                    b.HasIndex("Position");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("SpeciesUid");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UniqueName");

                    b.HasIndex("UniqueNameNormalized")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("VarietyId");

                    b.HasIndex("VarietyUid");

                    b.HasIndex("Version");

                    b.ToTable("Pokemon", "Pokemon");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.PokemonMoveEntity", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.Property<int>("MoveId")
                        .HasColumnType("integer");

                    b.Property<byte>("CurrentPowerPoints")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsMastered")
                        .HasColumnType("boolean");

                    b.Property<int?>("ItemId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ItemUid")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<byte>("MaximumPowerPoints")
                        .HasColumnType("smallint");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("MoveUid")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("PokemonUid")
                        .HasColumnType("uuid");

                    b.Property<int?>("Position")
                        .HasColumnType("integer");

                    b.Property<byte>("ReferencePowerPoints")
                        .HasColumnType("smallint");

                    b.HasKey("PokemonId", "MoveId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ItemUid");

                    b.HasIndex("MoveId");

                    b.HasIndex("MoveUid");

                    b.HasIndex("PokemonUid", "MoveUid")
                        .IsUnique();

                    b.ToTable("PokemonMoves", "Pokemon");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.RegionEntity", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RegionId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UniqueNameNormalized")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("RegionId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("DisplayName");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UniqueName");

                    b.HasIndex("UniqueNameNormalized")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.ToTable("Regions", "Pokemon");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.RegionalNumberEntity", b =>
                {
                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid>("RegionUid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpeciesUid")
                        .HasColumnType("uuid");

                    b.HasKey("SpeciesId", "RegionId");

                    b.HasIndex("RegionId", "Number")
                        .IsUnique();

                    b.HasIndex("RegionUid", "Number")
                        .IsUnique();

                    b.HasIndex("SpeciesUid", "RegionUid")
                        .IsUnique();

                    b.ToTable("RegionalNumbers", "Pokemon");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.SpeciesEntity", b =>
                {
                    b.Property<int>("SpeciesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpeciesId"));

                    b.Property<byte>("BaseFriendship")
                        .HasColumnType("smallint");

                    b.Property<byte>("CatchRate")
                        .HasColumnType("smallint");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<byte>("EggCycles")
                        .HasColumnType("smallint");

                    b.Property<string>("GrowthRate")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("PrimaryEggGroup")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SecondaryEggGroup")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UniqueNameNormalized")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("SpeciesId");

                    b.HasIndex("BaseFriendship");

                    b.HasIndex("CatchRate");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("DisplayName");

                    b.HasIndex("EggCycles");

                    b.HasIndex("GrowthRate");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("PrimaryEggGroup");

                    b.HasIndex("SecondaryEggGroup");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UniqueName");

                    b.HasIndex("UniqueNameNormalized")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.ToTable("Species", "Pokemon");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.TrainerEntity", b =>
                {
                    b.Property<int>("TrainerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrainerId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("License")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("LicenseNormalized")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Money")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PartySize")
                        .HasColumnType("integer");

                    b.Property<string>("Sprite")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UniqueNameNormalized")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("UserUid")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("TrainerId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("DisplayName");

                    b.HasIndex("Gender");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("License");

                    b.HasIndex("LicenseNormalized")
                        .IsUnique();

                    b.HasIndex("Money");

                    b.HasIndex("PartySize");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UniqueName");

                    b.HasIndex("UniqueNameNormalized")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("UserId");

                    b.HasIndex("UserUid");

                    b.HasIndex("Version");

                    b.ToTable("Trainers", "Pokemon");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.VarietyEntity", b =>
                {
                    b.Property<int>("VarietyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VarietyId"));

                    b.Property<bool>("CanChangeForm")
                        .HasColumnType("boolean");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("GenderRatio")
                        .HasColumnType("integer");

                    b.Property<string>("Genus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("SpeciesUid")
                        .HasColumnType("uuid");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UniqueNameNormalized")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("VarietyId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("DisplayName");

                    b.HasIndex("Genus");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("SpeciesUid");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UniqueName");

                    b.HasIndex("UniqueNameNormalized")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.HasIndex("SpeciesId", "IsDefault");

                    b.ToTable("Varieties", "Pokemon");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.VarietyMoveEntity", b =>
                {
                    b.Property<int>("VarietyId")
                        .HasColumnType("integer");

                    b.Property<int>("MoveId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("MoveUid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VarietyUid")
                        .HasColumnType("uuid");

                    b.HasKey("VarietyId", "MoveId");

                    b.HasIndex("Level");

                    b.HasIndex("MoveId");

                    b.HasIndex("MoveUid");

                    b.HasIndex("VarietyUid", "MoveUid")
                        .IsUnique();

                    b.ToTable("VarietyMoves", "Pokemon");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.BattlePokemonEntity", b =>
                {
                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.BattleEntity", "Battle")
                        .WithMany("Pokemon")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.PokemonEntity", "Pokemon")
                        .WithMany("Battles")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Battle");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.BattleTrainerEntity", b =>
                {
                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.BattleEntity", "Battle")
                        .WithMany("Trainers")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.TrainerEntity", "Trainer")
                        .WithMany("Battles")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Battle");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.EvolutionEntity", b =>
                {
                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.ItemEntity", "HeldItem")
                        .WithMany("HeldEvolutions")
                        .HasForeignKey("HeldItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.ItemEntity", "Item")
                        .WithMany("Evolutions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.MoveEntity", "KnownMove")
                        .WithMany("Evolutions")
                        .HasForeignKey("KnownMoveId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.FormEntity", "Source")
                        .WithMany("SourceEvolutions")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.FormEntity", "Target")
                        .WithMany("TargetEvolutions")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HeldItem");

                    b.Navigation("Item");

                    b.Navigation("KnownMove");

                    b.Navigation("Source");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.FormAbilityEntity", b =>
                {
                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.AbilityEntity", "Ability")
                        .WithMany("Forms")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.FormEntity", "Form")
                        .WithMany("Abilities")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.FormEntity", b =>
                {
                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.SpeciesEntity", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.VarietyEntity", "Variety")
                        .WithMany("Forms")
                        .HasForeignKey("VarietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Species");

                    b.Navigation("Variety");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.InventoryEntity", b =>
                {
                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.ItemEntity", "Item")
                        .WithMany("Inventory")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.TrainerEntity", "Trainer")
                        .WithMany("Inventory")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.ItemEntity", b =>
                {
                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.MoveEntity", "Move")
                        .WithMany("TechnicalMachines")
                        .HasForeignKey("MoveId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Move");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.PokemonEntity", b =>
                {
                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.TrainerEntity", "CurrentTrainer")
                        .WithMany("CurrentPokemon")
                        .HasForeignKey("CurrentTrainerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.FormEntity", "Form")
                        .WithMany("Pokemon")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.ItemEntity", "HeldItem")
                        .WithMany("HoldingPokemon")
                        .HasForeignKey("HeldItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.TrainerEntity", "OriginalTrainer")
                        .WithMany("OriginalPokemon")
                        .HasForeignKey("OriginalTrainerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.ItemEntity", "PokeBall")
                        .WithMany("ContainedPokemon")
                        .HasForeignKey("PokeBallId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.SpeciesEntity", "Species")
                        .WithMany("Pokemon")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.VarietyEntity", "Variety")
                        .WithMany("Pokemon")
                        .HasForeignKey("VarietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentTrainer");

                    b.Navigation("Form");

                    b.Navigation("HeldItem");

                    b.Navigation("OriginalTrainer");

                    b.Navigation("PokeBall");

                    b.Navigation("Species");

                    b.Navigation("Variety");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.PokemonMoveEntity", b =>
                {
                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.ItemEntity", "Item")
                        .WithMany("LearnedMoves")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.MoveEntity", "Move")
                        .WithMany("Pokemon")
                        .HasForeignKey("MoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.PokemonEntity", "Pokemon")
                        .WithMany("Moves")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Move");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.RegionalNumberEntity", b =>
                {
                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.RegionEntity", "Region")
                        .WithMany("RegionalNumbers")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.SpeciesEntity", "Species")
                        .WithMany("RegionalNumbers")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.VarietyEntity", b =>
                {
                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.SpeciesEntity", "Species")
                        .WithMany("Varieties")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.VarietyMoveEntity", b =>
                {
                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.MoveEntity", "Move")
                        .WithMany("Varieties")
                        .HasForeignKey("MoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeGame.EntityFrameworkCore.Entities.VarietyEntity", "Variety")
                        .WithMany("Moves")
                        .HasForeignKey("VarietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Move");

                    b.Navigation("Variety");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.AbilityEntity", b =>
                {
                    b.Navigation("Forms");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.BattleEntity", b =>
                {
                    b.Navigation("Pokemon");

                    b.Navigation("Trainers");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.FormEntity", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("Pokemon");

                    b.Navigation("SourceEvolutions");

                    b.Navigation("TargetEvolutions");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.ItemEntity", b =>
                {
                    b.Navigation("ContainedPokemon");

                    b.Navigation("Evolutions");

                    b.Navigation("HeldEvolutions");

                    b.Navigation("HoldingPokemon");

                    b.Navigation("Inventory");

                    b.Navigation("LearnedMoves");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.MoveEntity", b =>
                {
                    b.Navigation("Evolutions");

                    b.Navigation("Pokemon");

                    b.Navigation("TechnicalMachines");

                    b.Navigation("Varieties");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.PokemonEntity", b =>
                {
                    b.Navigation("Battles");

                    b.Navigation("Moves");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.RegionEntity", b =>
                {
                    b.Navigation("RegionalNumbers");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.SpeciesEntity", b =>
                {
                    b.Navigation("Pokemon");

                    b.Navigation("RegionalNumbers");

                    b.Navigation("Varieties");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.TrainerEntity", b =>
                {
                    b.Navigation("Battles");

                    b.Navigation("CurrentPokemon");

                    b.Navigation("Inventory");

                    b.Navigation("OriginalPokemon");
                });

            modelBuilder.Entity("PokeGame.EntityFrameworkCore.Entities.VarietyEntity", b =>
                {
                    b.Navigation("Forms");

                    b.Navigation("Moves");

                    b.Navigation("Pokemon");
                });
#pragma warning restore 612, 618
        }
    }
}
